name: BloomVale
version: '1.3.0'
main: dev.casperrs.bloomVale.BloomVale
description: BloomVale core functionalities
api-version: '1.21'
loader: dev.casperrs.bloomVale.papermc.BloomValeLoader
bootstrapper: dev.casperrs.bloomVale.papermc.BloomValeBootstrap
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true


